# Generated by Django 3.2.23 on 2023-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
