# Generated by Django 3.2.23 on 2023-11-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvite',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'member'), (8, 'administrator')], default=1),
        ),
    ]
