# Generated by Django 3.2.23 on 2023-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationinvite_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmembership',
            name='is_member_join_email_enabled',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_member_join_email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
