# Generated by Django 3.2.23 on 2023-11-26 21:24

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20231124_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_token',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 32}), max_length=40),
        ),
    ]
