# Generated by Django 3.2.23 on 2023-12-04 18:34

from django.db import migrations, models
import integraflow.core.utils.uuidt


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='id',
            field=models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='id',
            field=models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False),
        ),
    ]
