# Generated by Django 3.2.23 on 2024-05-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20231204_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='usage_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
