# Generated by Django 3.2.23 on 2023-12-11 19:16

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import integraflow.core.utils.uuidt


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_identified_user'),
        ('event', '0002_alter_propertydefinition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDefinition',
            fields=[
                ('id', models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_definitions', related_query_name='project', to='project.project')),
            ],
            options={
                'verbose_name': 'EventDefinition',
                'verbose_name_plural': 'EventDefinitions',
                'db_table': 'event_definitions',
            },
        ),
        migrations.AddIndex(
            model_name='eventdefinition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='index_event_definition_name', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='eventdefinition',
            unique_together={('project', 'name')},
        ),
    ]
