# Generated by Django 3.2.23 on 2023-12-12 21:59

from django.db import migrations, models
import integraflow.core.utils.uuidt


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20231211_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='person_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user_attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(db_index=True, default=integraflow.core.utils.uuidt.UUIDT, editable=False),
        ),
    ]
