# Generated by Django 3.2.23 on 2023-11-20 07:36

from django.db import migrations, models
import integraflow.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=integraflow.core.models.LowercaseSlugField(blank=True, max_length=48, null=True),
        ),
    ]
