# Generated by Django 3.2.23 on 2023-12-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_unique slug for organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttheme',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_themes', related_query_name='project_theme', to='project.project'),
        ),
        migrations.AlterModelTable(
            name='projecttheme',
            table='project_themes',
        ),
    ]
