# Generated by Django 3.2.23 on 2023-12-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20231204_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttheme',
            name='settings',
        ),
    ]
