# Generated by Django 3.2.23 on 2023-12-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_projecttheme_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identified_user',
            field=models.BooleanField(default=False),
        ),
    ]
