# Generated by Django 3.2.23 on 2023-11-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
