# Generated by Django 3.2.23 on 2023-11-28 22:05

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyquestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 16}), max_length=48),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='slug',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 16}), max_length=48),
        ),
    ]
