# Generated by Django 3.2.23 on 2023-12-04 18:34

from django.db import migrations, models
import integraflow.core.utils.uuidt


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20231204_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False),
        ),
    ]
