# Generated by Django 3.2.23 on 2023-12-04 22:13

from django.db import migrations, models
import integraflow.core.utils.uuidt


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_survey_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='slug',
        ),
        migrations.AlterField(
            model_name='surveychannel',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='surveychannel',
            name='id',
            field=models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, max_length=60,),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='id',
            field=models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SurveyQuestionOption',
        ),
    ]
