# Generated by Django 3.2.23 on 2023-12-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20231204_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveychannel',
            name='type',
            field=models.CharField(choices=[('email', 'email'), ('link', 'link'), ('api', 'api'), ('custom', 'custom'), ('mobile_app', 'mobile app'), ('web_app', 'web app')], default='link', max_length=40),
        ),
    ]
