# Generated by Django 3.2.23 on 2024-02-02 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools
import integraflow.core.utils.uuidt


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_identified_user'),
        ('survey', '0008_alter_surveychannel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveychannel',
            name='link',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 6}), max_length=48),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tag', to='project.project')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False)),
                ('response', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('in_progressin progress', 'In Progress'), ('completedcompleted', 'Completed'), ('archivedarchived', 'Archived')], default='in_progressin progress', max_length=40)),
                ('distinct_id', models.CharField(max_length=200)),
                ('person_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user_attributes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DateTimeField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', related_query_name='survey_response', to='survey.survey')),
            ],
            options={
                'verbose_name': 'SurveyResponse',
                'verbose_name_plural': 'SurveyResponses',
                'db_table': 'survey_responses',
            },
        ),
        migrations.CreateModel(
            name='ResponseTag',
            fields=[
                ('id', models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_tags', related_query_name='response_tag', to='survey.surveyresponse')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.tag')),
            ],
            options={
                'verbose_name': 'ResponseTag',
                'verbose_name_plural': 'ResponseTags',
                'db_table': 'response_tags',
            },
        ),
        migrations.CreateModel(
            name='ResponseNote',
            fields=[
                ('id', models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_notes', related_query_name='response_note', to='survey.surveyresponse')),
            ],
            options={
                'verbose_name': 'SurveyResponseNote',
                'verbose_name_plural': 'SurveyResponseNotes',
                'db_table': 'response_notes',
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique tag name for project'),
        ),
        migrations.AddConstraint(
            model_name='responsetag',
            constraint=models.UniqueConstraint(fields=('response', 'tag'), name='unique tag for response'),
        ),
    ]
