# Generated by Django 3.2.23 on 2024-02-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20240202_1905'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='surveychannel',
            constraint=models.UniqueConstraint(fields=('link',), name='unique_link_for_survey_channel'),
        ),
    ]
