# Generated by Django 3.2.23 on 2024-02-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_surveychannel_unique_link_for_survey_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
