# Generated by Django 3.2.23 on 2024-02-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_surveyresponse_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='type',
            field=models.CharField(choices=[('single', 'single'), ('multiple', 'multiple'), ('text', 'text'), ('date', 'date'), ('csat', 'csat'), ('ces', 'ces'), ('smiley_scale', 'smiley scale'), ('numerical_scale', 'numerical scale'), ('rating', 'rating'), ('nps', 'nps'), ('form', 'form'), ('boolean', 'boolean'), ('cta', 'cta'), ('dropdown', 'dropdown'), ('integration', 'integration'), ('custom', 'custom')], default='text', max_length=40),
        ),
    ]
