# Generated by Django 3.2.23 on 2024-05-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20240507_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='analytics_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='analytics_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
