# Generated by Django 3.2.23 on 2025-03-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20240511_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'SurveyResponse', 'verbose_name_plural': 'SurveyResponses'},
        ),
    ]
  
