# Generated by Django 3.2.22 on 2023-10-23 23:07

from django.db import migrations, models
import integraflow.core.utils.uuidt


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingRecord',
            fields=[
                ('id', models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, editable=False, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(max_length=1024)),
                ('campaign_key', models.CharField(max_length=128)),
                ('campaign_count', models.IntegerField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messaging_records',
                'unique_together': {('email_hash', 'campaign_key')},
            },
        ),
    ]
