# Generated by Django 3.2.23 on 2023-12-04 18:34

from django.db import migrations, models
import integraflow.core.utils.uuidt


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231023_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=integraflow.core.utils.uuidt.UUIDT, unique=True),
        ),
    ]
