# Generated by Django 3.2.23 on 2023-12-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
