# Generated by Django 3.2.22 on 2023-10-19 18:12

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import integraflow.core.utils.json_serializer
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=integraflow.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=integraflow.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('local', 'local'), ('thirdparty', 'thirdparty')], default='local', max_length=60)),
                ('identifier', models.CharField(blank=True, max_length=256, null=True)),
                ('about_app', models.TextField(blank=True, null=True)),
                ('data_privacy', models.TextField(blank=True, null=True)),
                ('data_privacy_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('support_url', models.URLField(blank=True, null=True)),
                ('configuration_url', models.URLField(blank=True, null=True)),
                ('app_url', models.URLField(blank=True, null=True)),
                ('manifest_url', models.URLField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=60, null=True)),
                ('audience', models.CharField(blank=True, max_length=256, null=True)),
                ('is_installed', models.BooleanField(default=True)),
                ('author', models.CharField(blank=True, max_length=60, null=True)),
                ('brand_logo_default', models.ImageField(blank=True, null=True, upload_to='app-brand-data')),
            ],
            options={
                'ordering': ('name', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=50)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('app_name', models.CharField(max_length=60)),
                ('manifest_url', models.URLField()),
                ('brand_logo_default', models.ImageField(blank=True, null=True, upload_to='app-installation-brand-data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('auth_token', models.CharField(max_length=128, unique=True)),
                ('token_last_4', models.CharField(max_length=4)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='app.app')),
            ],
        ),
        migrations.CreateModel(
            name='AppExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('mount', models.CharField(choices=[('navigation', 'navigation')], max_length=256)),
                ('target', models.CharField(choices=[('popup', 'popup'), ('app_page', 'app_page')], default='popup', max_length=128)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='app.app')),
            ],
        ),
        migrations.AddIndex(
            model_name='app',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='app_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='app_meta_idx'),
        ),
    ]
